# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='course.Course'),
        ),
    ]
