# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_description_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Validator',
        ),
    ]
